name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Build Solution
      run: |
        msbuild.exe Supernova.sln /nologo /p:platform="x86" /p:configuration="Release" /p:DefineConstants="PRERELEASE%3BTEN_BIT_BLOCKS"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Supernova
        path: "./bin/Release"        
